### ISSUE TITLE
Eu, como desenvolvedor, desejo remover a senha hardcoded do arquivo EmailController.ts

### ISSUE THREAD

**Issue by EuricoAbreu** [fga-eps-mds/2021.2-Noctua#118]
## Descrição da Issue
Remocao da senha do arquivo EmailController.ts

## Tasks:
- [x] Remover a senha do EmailController.ts
- [x] Adicionar variavel de ambiente da senha do email

## Critérios de Aceitação:
- [x] O codigo deve estar funcional e nao ter mais credenciais hardcoded
