### ISSUE TITLE
Adição de Política nos docs

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#37]
## Descrição da Issue
Criação de politicas e template.

## Tasks:
- [x] Política de commit
- [x] Política de branch
- [x] Template

## Critérios de Aceitação:
- [x] Todas as políticas criadas.
