### ISSUE TITLE
Eu, como usuário, gostaria de filtrar os dados disponibilizados para que os resultados estejam de acordo com o que desejo.

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#73]
## Descrição da Issue
Filtrar os dados das tabelas do salário dos magistrados.

## Tasks:
- [ ] Desenvolver o back end para recuperar esses dados.
- [ ] Criar o Metabase para visualizar os dados.
- [ ] Desenvolver uma página de front básica para testes

## Critérios de Aceitação:
- [ ] Filtro de dados buscando os salários dos magistrados
- [ ] Visualização dos dados em dashboard

**Comment by RochaCarla** [comment]
Essa issue está muito grande e complexa pra ser resolvida em uma sprint. Já parece ser uma dívida técnica e não tem report na issue do que ja foi feito.

Sugestões:
- Fazer report do que já foi feito
- Detalhar de forma mais refinada as tarefas a serem feitas para conseguirem dimensionar a complexidade
- Quebrar em mais issues menores
- Alocar mais duplas
