### ISSUE TITLE
Eu, como usuário, gostaria de visualizar os salários dos magistrados para poder fazer futuras análises.

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#74]
## Descrição da Issue
Visualizar os salários dos magistrados para fazer análises.

## Tasks:
- [ ]  Desenvolver um dashboard que mostre os dados dos salários.
- [ ]  Adicionar o dashboard no front.

## Critérios de Aceitação:
- [ ]  Visualizar através da sessão o salário dos magistrados.

**Comment by RochaCarla** [comment]
Dar o report da issue
ela ta muito genérica.

**Comment by RochaCarla** [comment]
Cadê o pareamento?
