### ISSUE TITLE
Eu como desenvolvedor, gostaria de adicionar template de issue.

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#75]
## Descrição da Issue
Criar e adicionar ao repositório o template de issue.

## Tasks:
- [x] Criar o template de issue
- [x] Adicionar ao repositório

## Critérios de Aceitação:
- [x] Template de issue com assigness, labels, projects e milestone.
