### ISSUE TITLE
Eu como desenvolvedor, gostaria de adicionar o template de pull request.

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#77]
## Descrição da Issue
Criar e adicionar ao repositório o template de pull request.

## Tasks:
- [x] Criar o template de pull request
- [x] Adicionar ao repositório

## Critérios de Aceitação:
- [x] Template de pull request.
