### ISSUE TITLE
Eu como desenvolvedor , gostaria de adicionar dados de salários dos magistrado para o banco de dados MongoDB.

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#84]
## Descrição da Issue
Adicionar dados do Brasil.io para o banco de dados MongoDB

## Tasks:
- [x] Pegar os arquivos em formato csv
- [x] Adicionar os dados ao MongoDB
- [x] Inicio do metabase

## Critérios de Aceitação:
- [x] Adicionar os dados ao banco de dados MongoDB

**Comment by fellipepcs** [comment]
Irei quebrar ela em outras issues, e especificar melhor o que se pede.
