### ISSUE TITLE
Estudo para implementação do Metabase (BI)

### ISSUE THREAD

**Issue by EuricoAbreu** [fga-eps-mds/2021.2-Noctua#85]
Estudo para conhecer a ferramenta de BI sugerida pela professora e aprender como implementar.

## Tasks:
- [x] Estudo básico da ferramenta
- [x] Leitura da documentação
- [x] Fazer o deploy da ferramenta em uma máquina local para melhor entender o funcionamento na prática
- [x] Passar os conhecimentos adquiridos a todos do grupo
- [x] Comentar aqui fontes de estudo para quem queira se aprofundar mais

## Critérios de Aceitação:
- [x] Colocar as fontes e materiais de estudo nessa issue
- [x] Trocar o conhecimento adquirido entre o grupo

**Comment by EuricoAbreu** [comment]
Documentação:
- https://www.metabase.com/docs/latest/

Parte da documentação que considero mais importante
- https://www.metabase.com/docs/latest/operations-guide/installing-metabase.html
- https://www.metabase.com/docs/latest/setting-up-metabase.html
- https://www.metabase.com/learn/getting-started/getting-started.html

Vídeo no youtube do canal da própria metabase:
(Metabase tutorial: everything you need to know to get started in under 20 min)
- https://www.youtube.com/watch?v=4bNp906oOhs
