### ISSUE TITLE
Eu como desenvolvedor , gostaria de filtrar informações do banco de dados para o Metabase

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#86]
## Descrição da Issue
FIltrar informações do banco de dados

## Tasks:
- [ ] Filtrar informações para o Back End
- [ ] Adicionar informações no Metabase

## Critérios de Aceitação:
- [ ] Filtrar e adicionar as informações para o Back End e o Metabase.
