### ISSUE TITLE
Eu como desenvolvedor, gostaria de criar a página "Salário dos Magistrados"

### ISSUE THREAD

**Issue by matheusmsvieira** [fga-eps-mds/2021.2-Noctua#90]
## Descrição da Issue
Incluir a página "Salários dos Magistrados" dentro da pasta page.

## Tasks:
- [ ]  Criar o arquivo .tsx.
- [ ] Alinhar o layout com as outras páginas.
- [ ] Começar a inserir as informações do metabase.

## Critérios de Aceitação:
- [ ]  Visualizar a página "Salários dos Magistrados" com layout padrão.
