### ISSUE TITLE
Eu como desenvolvedor, gostaria de criar os testes automatizados com Cypress

### ISSUE THREAD

**Issue by matheusmsvieira** [fga-eps-mds/2021.2-Noctua#91]
## Descrição da Issue
Criar testes automatizados para testar o front-end.

## Tasks:
- [x] Configurar o ambiente dos testes.
- [x] Criar scripts de teste com base nas features.

## Critérios de Aceitação:
- [x] Conseguir rodar as suítes de teste.
