### ISSUE TITLE
Eu como desenvolvedor, gostaria de criar o metabase para o desenvolvimento do dashboard

### ISSUE THREAD

**Issue by fellipepcs** [fga-eps-mds/2021.2-Noctua#94]
## Descrição da Issue
Iniciar o metabase para criação do dashboard inicial.
## Tasks:
- [x]  Introduzir no ambiente Docker o metabase
- [x] Iniciar o ambiente
- [x] Adicionar uma pagina inicial do tema Salários dos magistrados.

## Critérios de Aceitação:
- [x]  Visualizar o dashboard "Salários dos Magistrados" com layout padrão.
